x-deploy-policy: &x-deploy-policy
  mode: global
  resources:
    limits:
      memory: 128M
    reservations:
      memory: 64M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  prometheus_agents:
    name: prometheus_agents
    external: true

configs:
  node-meta.prom:
    template_driver: golang
    file: node-meta.prom

services:
  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:?NODE_EXPORTER_VERSION env is not set}
    command:
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--path.rootfs=/rootfs'
      - '--no-collector.ipvs'
    environment:
      NODE_ID: "${NODE_ID:-{{.Node.ID}}}"
      NODE_NAME: "${NODE_NAME:-{{.Node.Hostname}}}"
    networks:
      - prometheus_agents
    volumes:
      - /:/rootfs:ro,rslave
    configs:
      - source: node-meta.prom
        target: /etc/node-exporter/node-meta.prom
    deploy: 
      <<: *x-deploy-policy
      labels:
        io.prometheus.enable: "true"
        io.prometheus.port: "9100"
    logging: *x-default-logging

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:?CADVISOR_VERSION env is not set}
    command: -logtostderr -docker_only
    networks:
      - prometheus_agents
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy: 
      <<: *x-deploy-policy
      labels:
        io.prometheus.enable: "true"
        io.prometheus.port: "8080"
    logging: *x-default-logging
